Четвертое задание
yaoyao668/FastAPI pull request #2
Opened 2024-12-10 20:46 UTC by yaoyao668

Здравствуйте, учитель, это четвертое задание, войдите в систему по электронной почте.

2024-12-12 15:10 UTC, vladefr97 requested changes

2024-12-12 15:10 UTC, vladefr97 commented on AuthService/app/main.py
> +# 包含路由
Пиши комментарии на английском

2024-12-12 15:10 UTC, vladefr97 commented on AuthService/app/config.py
> +SECRET_KEY = "926e3c3b282f22e6c09ed7f3824deedc37993d40e6f90c08c2bc07cbf710fca6"
Нельзя заливать в проект реальную секретную информацию

2024-12-12 15:10 UTC, vladefr97 commented on AuthService/app/auth.py
> +def create_access_token(data: dict, expires_delta: timedelta = None):
Желательно разнести все по отдельным файлам

2024-12-12 17:28 UTC, yaoyao668 commented on AuthService/app/auth.py
> +def create_access_token(data: dict, expires_delta: timedelta = None):
Здравствуйте, учитель, я изменил программу по мере необходимости, пожалуйста, проверьте ее.

2025-01-16 19:14 UTC, vladefr97 approved these changes

2025-01-17 08:11 UTC, merged